title: IAAML-2020
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The prime objective of the conference is to bring together
  academicians, researchers, industrialists, scientists, entrepreneurs,
  faculty and students to share their knowledge in cutting edge
  technologies, innovations and recent trends in the field of intelligent
  information systems. It gives a platform to showcase their theoretical
  concepts, systems architecture
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
