title: IAAML-2020
big_title: Innovative Application of AI and Machine Learning
email: nciaaml2020@gmaiI.com
date: 27<sup>th</sup> - 28<sup>th</sup>, February, 2020
date1: 6<sup>th</sup> Feb 2019
date2: 15<sup>th</sup> Feb 2019
date3: 25<sup>th</sup> Feb 2019
fee1: 1500
fee2: 2000
phone: 044-2747426
mobile: +91 8637635755
keywords: conference
address: The Convenor, NCIAAML 2020, Department of Computer Science and Engineering, Hindustan Institute of Technology and Science, Rajiv Gandhi Salai (OMR), Padur, Chennai 603 103.
description: >- # this means to ignore newlines until "baseurl:"
  The prime objective of the conference is to bring together
  academicians, researchers, industrialists, scientists, entrepreneurs,
  faculty and students to share their knowledge in cutting edge
  technologies, innovations and recent trends in the field of intelligent
  information systems. It gives a platform to showcase their theoretical
  concepts, systems architecture
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
